Feature/as/bg aesthetic
DManuel010/TheGangProject pull request #11
Opened 2020-02-11 22:57 UTC by simpsona4

I made it so that the background image on SMITE Builder has an increasing blur filter as the user scrolls down.  
I'm not sure how you want the css to be organized.  By default, I isolated SMITE Builder's css and gave it its own class so that it doesn't affect the other pages.

2020-02-11 23:24 UTC, bdatdo0601 commented
Check out the comment github bot already made. As for css. I was thinking maybe it's a good idea to integrate less instead of just using pure css http://lesscss.org/

2020-02-13 01:17 UTC, bdatdo0601 approved these changes
I like the fact that it is now separated. Great progress! LGTM

2020-03-03 02:07 UTC, DManuel010 approved these changes

2020-03-30 00:28 UTC, bdatdo0601 approved these changes
Lgtm

2020-04-09 22:44 UTC, bdatdo0601 requested changes
Your history is now messed up. please fix before merge

2025-02-26 14:38 UTC, closed without merging