feat:  backend setup (python and django)
DManuel010/TheGangProject pull request #7
Opened 2020-02-02 18:03 UTC by DManuel010

- configured python3 setup
- configured django setup
- use virutalenv and requirements.txt to setup your own python3 virtual environment + dependencies

2020-02-02 18:55 UTC, bdatdo0601 commented
I think it's a good idea to move these in a separate directory like `django-backend`

2020-02-02 19:10 UTC, simpsona4 approved these changes
Self-Note: Beginnings of user auth, and other backend functionalities.

2020-02-02 19:12 UTC, bdatdo0601 requested changes
We also going to need a readme documentation on how to set it up

2020-02-02 19:19 UTC, bdatdo0601 commented on requirements.txt
> +pymongo==3.10.1
This should sit within `django-backend` file since this is only related to Python

2020-02-03 03:31 UTC, bdatdo0601 requested changes
Looks good to start! But you probably need to rebase with dev

2020-02-04 02:10 UTC, bdatdo0601 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Python and DJango setup](https://trello.com/c/4wVuwVAB/50-python-and-django-setup)

2020-02-04 03:30 UTC, bdatdo0601 approved these changes
LGTM!

2020-02-04 03:35 UTC, merged